on: [push]

jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: alexanderschau/ipfs-pinning-action@v1.0.0
      with:
        path_to_add: 'smplus.pages.dev/ipfs/' 
        endpoint: ‘https://api.filebase.io/v1/ipfs/pins’
        access_token: ${{ secrets.ACCESS_TOKEN }} 
        pin_name: 'smplus-hypermedia'
